Update versions for dependencies
- tera pinned to 1.19.1 to fix "error[E0599]: no method named `len` found for struct `Pairs<'i, R>` in the current scope"
- anyhow, clap, filetime, nix, regex, serde, serde_json, serde_yaml updated to latest compatible versions